name: Publish

on:
  push:
    # tags:
    #   - 'v*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            command: npm run pack:linux
            binFileName: "europa_linux_amd64"
            appName: "Europa-UI-1.0.0.AppImage"
          - os: windows-latest
            command: npm run pack:win
            binFileName: "europa_win.exe"
            appName: "Europa-UI Setup 1.0.0.exe"

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "patractlabs/europa"
          version: "test"
          file: ${{ matrix.binFileName }}
          target: build/${{ matrix.binFileName }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: ${{ matrix.command }}
      - name: Upload applications to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: dist/${{ matrix.appName }}
          asset_name: ${{ matrix.appName }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Hello Electron"
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     include:
    #       - os: ubuntu-latest
    #         artifact_name: mything
    #         asset_name: mything-linux-amd64
          # - os: windows-latest
          #   artifact_name: mything.exe
          #   asset_name: mything-windows-amd64
          # - os: macos-latest
          #   artifact_name: mything
          #   asset_name: mything-macos-amd64

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}